# Generated by Django 4.2.7 on 2023-12-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_band_image_cake_image_dress_image_flower_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='name',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
    ]
