# Generated by Django 4.2.7 on 2023-12-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_alter_band_price_alter_cake_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
