# Generated by Django 4.2.7 on 2023-12-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='type',
            field=models.CharField(choices=[('Open Venue', 'Open Venue'), ('Closed Venue', 'Closed Venue')], default='option2', max_length=50),
        ),
    ]
